### ISSUE TITLE
Verification email is not visable in Windows Mails App

### ISSUE THREAD

**Issue by wycers** [SUSTechFlow/server#1]
In the Mail app, there's only a title without any content.
![20200223205055](https://user-images.githubusercontent.com/17094433/75112379-3bf4fa00-567e-11ea-880a-5ed7cd45c904.png)

It's very strange and users may get confused.

**Comment by jwnhy** [comment]
I doubt it's an issue on our end.
Most likely it's an issue of Microsoft mail app.
But I still find some suggestion from Microsoft official support.

https://answers.microsoft.com/en-us/windows/forum/apps_windows_10-outlook_mail/the-mail-app-in-windows-10-not-showing-content-for/b3cd9086-1b36-4018-882e-ee1bae03e723

And since it's not a problem on our end. You may as well consider to ask Microsoft to fix it. Closing.
